language: python
python:
- '3.4'
- '3.5'
env:
- DRIVER=pymongo
- DRIVER=motor
- DRIVER=txmongo
before_install:
- travis_retry sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install mongodb-org
- sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
- mongo --version
install:
- pip install -U tox
- pip install -U coveralls
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION-$DRIVER | tr -d .)
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: touilleMan
  password:
    secure: N5oj/7qsMQykhuhGE9uXEEyhZXDzRceBV047Z1iFxZKPv2hzimrTqY0Zb87hIeSDCmQEowtVsSD40vSHJ9bqdOKmiCYKRLwgAHDs5RepAtszZmCLNWQS/oiwIXrGzg3kqitxvaym1p4aK4ykUUQo8mBsii8WKxefa5esAZG49ovOEPKaywtAiC7De48ChYoxUnJhcKVDxUTBntORsP81F7gmibbZVeB97nVOzmjWnwlfVrEZ83Oq/rGpbPiK/ydYKonrmDVfrHGuhNS41ZpXqR0UlDSa7OWuw/dB5jZQDUtw57la/7FLuBtoGP5EbOUsWiy6+Kc3pEWrx2EupLKILzVezL27frTW41Y7mkhxkS2gu72BlEIdzUqUG+1/MVWzFbidn7auQ7DZeWH6/rFER/PmCzg7Mfkkomgu/Avqcu+sS4ZevVQfN67Lawk8rHvD8g79xSopfr4W55enss4QA5Kf2ICH3mjBuP9PubgJplHyqHf2hvtGc0ycvVxogzk3Ss7fIxg1UuonuW01Se28Fh06cMYaH0qjs06QDisv9qxrM1TTK81yRbzPqAyjxkqpXLLh8pM5BehkBwel7uVT4obDwvgk/mOpC4XKNSLUa6TjSApGe1QorA3E6kD+6Cr/4YLEcFYUlUtF6JFkT3KkqNlYaDNEM5RhRyeeaUYuIEU=
  on:
    tags: true
    repo: touilleMan/umongo
    condition: $TRAVIS_PYTHON_VERSION == '3.4'
