trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

stages:
  - stage: lint
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs: [lint]
          coverage: false
  - stage: test_mongo_4_2
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs:
            - py39-pymongo
            - py39-motor
            - py39-txmongo
          coverage: true
          pre_test:
              - script: |
                  sudo rm /etc/apt/sources.list.d/mongodb-org-4.4.list
                  wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
                  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
                  sudo apt-get remove '^mongodb-org.*'
                  sudo apt-get update
                  sudo apt-get install -y mongodb-org
              - script: mongod --version
              - script: sudo systemctl start mongod
  - stage: test_mongo_4_4
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs:
            - py37-pymongo
            - py37-motor
            - py37-txmongo
            - py39-pymongo
            - py39-motor
            - py39-txmongo
          coverage: true
          pre_test:
              - script: mongod --version
              - script: sudo systemctl start mongod
  - stage: release
    jobs:
      - template: job--pypi-release.yml@sloria
